== Rust - What's the Big Idea?

[quote, Alan Perlis]
A language that doesn't affect the way you think about programming, is not worth knowing.

Rust's big idea is _ownership_.

Ownership, and a distinction between moving and copying data.

Ok, two big ideas.

Ownership, a distinction between moving and copying data, and zero-overhead abstractions.

Ok, three big ideas. 

All three support Rust's principle goal: memory safety without runtime overhead.


=== Ownership, Transferring Ownership, and Borrowing

Rust's novel feature, which makes it a "perlis language" in my book, is that by default values are moved, not copied, by default.

... more to come...

This program does not compile.

-------------------------------------------------------
include::../src/file-ownership-err.rs[]
-------------------------------------------------------

Error:

-------------------------------------------------------
include::file-ownership-err.compile-output[]
-------------------------------------------------------

=== Message-Passing Concurrency

TODO

Rust's ownership model extends to concurrency.  Disallows data races.



=== Zero-Overhead Abstractions

